//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int id { get; set; }
        public string shortname { get; set; }
        public string name { get; set; }
        public Nullable<int> phonecode { get; set; }
        public string fromtime { get; set; }
        public string totime { get; set; }
    }
}
